name: test env
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Check Boot Config
        run: cat /boot/config-$(uname -r) | grep LSM
      
      - name: Check LSM
        run: cat /sys/kernel/security/lsm

      - name: run bpftool feature check
        run: sudo bpftool feature probe | grep -n -C 2 lsm

      - name: execute local binary
        run: sudo ./testlsm &

      - name: capture printk logs
        run: sudo cat /sys/kernel/debug/tracing/trace_pipe > test.log &     

      - name: test lsm prog
        run: |
          sleep 1
          cat test.log
