name: test env
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Check Boot Config
        run: cat /boot/config-$(uname -r) | grep LSM
      
      - name: Check LSM
        run: cat /sys/kernel/security/lsm

      - name: run bpftool feature check
        run: sudo bpftool feature probe | grep -n -C 2 lsm

      - name: execute local binary
        run: sudo ./testlsm
